### ISSUE TITLE
Volume control background

### ISSUE THREAD

**Issue by DDZ57** [jpfleury/clearlooks-phenix#13]
When I click the speaker icon in LXPanel, it seems the background color overflows the "Volume" frame.
I can see this with a CRT monitor.

![volume](https://cloud.githubusercontent.com/assets/2294605/4589640/71d178bc-5056-11e4-818f-be022baa5c5d.png)

Is it due to a Clearlooks-Phénix bug?
Thank you in advance and have a nice day!

**Comment by jpfleury** [comment]
There's a new release (Clearlooks-Phénix v7) that supports GTK 3.20. I don't plan to support older versions, so I close this report, but anyone can make a pull request.
