### ISSUE TITLE
White (#FFFFFF) band in printing dialog box

### ISSUE THREAD

**Issue by DDZ57** [jpfleury/clearlooks-phenix#14]
Hello!

There is a white band in the printing dialog box at preview, cancel, print buttons level I can see with a CRT monitor.

![imprimer](https://cloud.githubusercontent.com/assets/2294605/4589738/df82de72-5057-11e4-82ff-476d74837a92.png)

Is it due to Clearlooks-Phénix bug?
Thank you in advance and have a nice day!

**Comment by jpfleury** [comment]
There's a new release (Clearlooks-Phénix v7) that supports GTK 3.20. I don't plan to support older versions, so I close this report, but anyone can make a pull request.
