### ISSUE TITLE
Pressed buttons haven't got any border in pavucontrol

### ISSUE THREAD

**Issue by DDZ57** [jpfleury/clearlooks-phenix#15]
Hello!

In pavucontrol (Pulse audio volume controller), pressed buttons haven't got any border.

![pavucontrol](https://cloud.githubusercontent.com/assets/2294605/4589782/80045376-5058-11e4-8120-5fd17722af39.png)

Is it due to a Clearlooks-Phénix bug?
Thank you in advance and have a nice day!

**Comment by jpfleury** [comment]
There's a new release (Clearlooks-Phénix v7) that supports GTK 3.20. I don't plan to support older versions, so I close this report, but anyone can make a pull request.
