### ISSUE TITLE
Darklooks-Phénix, the Clearlooks-Phénix dark version?

### ISSUE THREAD

**Issue by DDZ57** [jpfleury/clearlooks-phenix#16]
Hello!

I tried to create the Clearlooks-Phénix dark version based on Darklooks GTK+ 2 theme. I think it will be a nice idea because the more time spends, the more clear version hurts my eyes due to hours spent front of the monitor screen.
So I changed the Clearlooks-Phénix color scheme by the Darklooks one, the core_color_b by the Darklooks' bg_color (because they're the same) then calculated the core_color_a basing on the Darklooks' selected_bg_color and these two colors value in Clearlooks-Phénix.
Unfortunately, the result isn't very well. In comparaison with Darklooks, some colors don't match and the are visual bugs.

![a widget factory - darklooks-phenix - gtk2](https://cloud.githubusercontent.com/assets/2294605/4590035/2a10b3ee-505b-11e4-9b89-5e6c99545038.png)

![a widget factory - darklooks-phenix - gtk3](https://cloud.githubusercontent.com/assets/2294605/4590042/2e3e6092-505b-11e4-92a2-8b1086f9f808.png)

gtk_color_scheme = "fg_color:#E6E6E6\nbg_color:#555753\nbase_color:#2E3436\ntext_color:#D3D7CF\nselected_bg_color:#3F403D\nselected_fg_color:#7AA3CC\ntooltip_bg_color:#EDDE5C\ntooltip_fg_color:#000000"

core_color_a=#5d574c
core_color_b=#555753

How to proceed as quickier and easier as possible?
Thank you in advance and have a nice day!

**Comment by Lesik** [comment]
Clearlooks Phénix is probably the best working "legacy" GTK3 theme. I agree that it's a good idea to port Clearlooks-Dark and/or Clearlooks-Colors using this theme as basis.

**Comment by jpfleury** [comment]
Hi,

I'm closing this report. I chose to not support (myself) color versions. I already have 6 Clearlooks-Phénix versions for different GTK versions and it's not yet compatible with GTK 3.16 and 3.18 (so more versions are needed). Honestly, I'm so tired of seeing my theme breaking at each new GTK version. It's too much work, and I no longer have any fun maintaining this theme.

Of course, I'll be happy to merge pull requests if someone works on that, but I won't look at it myself. Sorry. :-(

**Comment by Lesik** [comment]
It is saddening, but I can comprehend your decision. I'm aware of the horrible state of GTK 3 and themes.

It's better to have one working, beautiful Clearlooks than ten of them, of which none work correctly with the new GTK version. I agree it makes more sense to concentrate on that.

**Comment by prikhi** [comment]
I love this theme & I love dark themes so I may take this on in the future. I'm not familiar with GTK3 theme packaging though, would it be possible to create a separate theme by overriding the main theme files? Or would I have to create a fork?
