### ISSUE TITLE
Cairo reports invalid value errors when clearlooks-phenix is in use

### ISSUE THREAD

**Issue by foresto** [jpfleury/clearlooks-phenix#18]
When clearlooks-phenix is in use, cairo applications produce the following error message:

    cairo.Error: invalid value (typically too big) for the size of the input (surface, pattern, etc.)

For example, I see this message dozens or hundreds of times when using meld to compare git repository subdirectories. This does not occur with other gtk 3.0 themes.

I'm using clearlooks-phenix 6.0.3 on Xubuntu 15.04 with the Mist icon theme.

**Comment by jpfleury** [comment]
There's a new release (Clearlooks-Phénix v7) that supports GTK 3.20. I don't plan to support older versions, so I close this report, but anyone can make a pull request.
