### ISSUE TITLE
Black background in evince

### ISSUE THREAD

**Issue by KarelLebeda** [jpfleury/clearlooks-phenix#23]
Some time ago, I started having problems with evince (aka the Document Viewer) showing black background (see the screenshot). Besides not liking black backgrounds (one of the main reasons for using Phenix Clearlooks), it's actually hard working without sliders and stuff... I think this has happened after some recent Ubuntu update (I don't have control over these on my machine), but can't be sure. I'm running Ubuntu 12.04 with GTK 3.4.2. Is there anything I can do? Is it a bug?
![evince](https://cloud.githubusercontent.com/assets/10421244/11206491/5b2a6170-8d07-11e5-8797-7671cb5d2152.png)

**Comment by jpfleury** [comment]
Hi,

It's definitely a bug. Clearlooks-Phénix should not have any dark background. How did you install the theme? Is it installed in your folder `$HOME/.theme`, or via a deb package?

**Comment by KarelLebeda** [comment]
Hi,
I just unpacked https://github.com/jpfleury/clearlooks-phenix/archive/v2.zip into ~/.themes...

Originally, I had some older version, I assume (the README file mentions "**Clearwaita = Clearlooks + Adwaita**" and "- [Download the archive of the latest version.](https://gitorious.org/projets-divers/clearlooks-phenix/archive/v1.zip)"). So I thought it's incompatible with some recent Ubuntu update (we have our machines managed by the university IT and they run nightly updates, so I sometimes come to my computer in the morning with something random not working) and tried to get the latest version. So I downloaded v2 from here, for my GTK version, but it does exactly the same (although some other things work better)...

**Comment by legovini** [comment]
@jpfleury I'm having the same issue with Debian unstable and clearlooks-phenix 6.0.3 installed using the .deb package. The window manager I'm using is i3.

**Comment by jpfleury** [comment]
You both have this problem only with Evince?

**Comment by KarelLebeda** [comment]
Well, I have some problems with some non-Gnome applications such as Skype or Krusader, but those are different and probably unrelated, so my answer is "YES"...

**Comment by jpfleury** [comment]
There's a new release (Clearlooks-Phénix v7) that supports GTK 3.20. I don't plan to support older versions, so I close this report, but anyone can make a pull request.
