### ISSUE TITLE
GTK 3.16

### ISSUE THREAD

**Issue by aik** [jpfleury/clearlooks-phenix#24]
Hi!

Any plan on supporting GTK 3.16 (came with Fedora22)? Thanks!

**Comment by DDZ57** [comment]
To do this, theme developpers must:

– download the last GTK minor'S version (ex. here: GTK 3.16.7)
– extract the gtk+-3.16.7/gtk/theme/Adwaita folder
– read the README file then the SASS documentation at http://sass-lang.com/documentation
– etc

**Comment by aik** [comment]
this is basically a piece of advice to write my own theme. how do any of these instructions relate to clearlooks-phenix and its support of 3.16.7?

**Comment by DDZ57** [comment]
This means Clearlooks-Phenix must be converted to SASS to work with GTK >= 3.16

**Comment by Lamieur** [comment]
Fedora 23 comes with GTK+ 3.18.5 and even gtk3-demo's main window looks awful with additional border and disappearing top/down of the tree view (bundled Clearlooks-Phénix is 6.0.3) :(

**Comment by sorki** [comment]
@Lamieur any pointers where does this come from? I also see some issues with tree view and also flickering/disappearing scrollbars.

Tried 
```gsettings set org.gnome.desktop.interface enable-animations false```
but it doesn't seem to help.

**Comment by Lamieur** [comment]
There are animations that play when you "push" the top/bottom, but there are also a "..." marks when there's more of the list above/below your view. Both are missing in Clearlooks-Phénix.

Try the MATE Themes, "TraditionalOk" family looks like an actively maintained fork of this one.

**Comment by sorki** [comment]
Is it rewritten to SASS?

Btw I'm maintaing clearlooks-phenix in Fedora so fixing stuff is not a problem.

**Comment by Lamieur** [comment]
Looks pure CSS to me, which is no problem as long as it works and someone maintains it? :)

(Just dnf install mate-themes, you'll see)

**Comment by sorki** [comment]
Yup. The only problem is the awareness - people who use clearlooks-phenix not knowing about mate's TraditionalOk. I'll try to diff their theme and this one and we will see if it's worth backporting

**Comment by jpfleury** [comment]
There's a new release (Clearlooks-Phénix v7) that supports GTK 3.20. I don't plan to support GTK 3.16, so I close this report, but anyone can make a pull request about GTK 3.16.
