### ISSUE TITLE
Combo boxes

### ISSUE THREAD

**Issue by DDZ57** [jpfleury/clearlooks-phenix#25]
Hello!

I started gtk3-demo (GTK 3.14.15 version and Clearlooks-Phenix 6.0.3), opened the combo boxes widget and I got this screenshot:
[Combo boxes.pdf](https://github.com/jpfleury/clearlooks-phenix/files/43118/Combo.boxes.pdf)

The sub menu at right is shown with selected bg color rather than the base bg like the menu at left.

**Comment by jpfleury** [comment]
Ah ouais, je n'avais jamais vu ce bogue. Est-ce que tu as un exemple d'application utilisant ce widget?

**Comment by DDZ57** [comment]
Je n'avais jamais vu cette bogue auparavant non plus car, sauf exception, mes logiciels utilisant GTK s'appuient sur la version 2.Je n'ai pas d'exemple d'application utilisant cet élément d'interface graphique en tête. Si j'en trouve une, je vous le fait savoir. 
 


    Le Mardi 24 novembre 2015 20h47, Jean-Philippe Fleury <notifications@github.com> a écrit :
 
 

 Ah ouais, je n'avais jamais vu ce bogue. Est-ce que tu as un exemple d'application utilisant ce widget?—

**Comment by jpfleury** [comment]
There's a new release (Clearlooks-Phénix v7) that supports GTK 3.20. I don't plan to support older versions, so I close this report, but anyone can make a pull request.
