### ISSUE TITLE
GtkLevelBar are not themed: fixed

### ISSUE THREAD

**Issue by DDZ57** [jpfleury/clearlooks-phenix#26]
Clearlooks-Phenix 6.0.3 and GTK 3.14.15

In gtk.css

/*****************
 * error/warning/success *
 *****************/

@define-color error_color #cc0000;

@define-color warning_bg_color #faad3d;

@define-color success_color #4e9a06;

In gtk-widgets.css

/****************
 * Level *
 ****************/

/* level bars as used for password quality or remaining power */

GtkLevelBar {
    -GtkLevelBar-min-block-width: 34;
    -GtkLevelBar-min-block-height: 3;
}

GtkLevelBar.vertical {
    -GtkLevelBar-min-block-width: 3;
    -GtkLevelBar-min-block-height: 34;
}

.level-bar.trough {
    padding: 2px;
}

.level-bar.fill-block {
    border-width: 1px;
    border-style: solid;
    border-color: @scale_trough_highlight_border_color;
    background-color: @scale_trough_highlight_bg_color;
}

.level-bar.indicator-continuous.fill-block {
    padding: 2px;
    border-radius: 2px;
}

.level-bar.fill-block:backdrop,
.level-bar.fill-block.level-high:backdrop,
.level-bar.fill-block.level-low:backdrop {
    background-color: @insensitive_bg_color;
    border-color: @insensitive_border_color;
    background-image: none;
}

.level-bar.indicator-discrete.fill-block.horizontal {
    margin: 0 1px;
}

.level-bar.indicator-discrete.fill-block.vertical {
    margin: 1px 0;
}

.level-bar.fill-block.level-high {
    border-color: shade(@success_color, 0.85);
    background-image: linear-gradient(to bottom,
                                      shade(@success_color, 1.2),
                                      @success_color 75%,
                                      shade(@success_color, 0.95)
                                      );
}

.level-bar.fill-block.level-low {
    border-color: shade(@warning_bg_color, 0.80);
    background-image: linear-gradient(to bottom,
                                      shade(@warning_bg_color, 1.3),
                                      @warning_bg_color 75%,
                                      shade(@warning_bg_color, 0.90)
                                      );
}

.level-bar.fill-block.empty-fill-block {
    background-color: transparent;
    background-image: none;
    border-color: alpha(@theme_bg_color, 0.1);
}

.level-bar.fill-block.empty-fill-block:backdrop {
    border-color: transparent;
    background-color: transparent;

**Comment by jpfleury** [comment]
Est-ce que tu aurais une capture d'écran pour illustrer?

**Comment by DDZ57** [comment]
Bien sûr ! ;-)

![a widget factory - clearlooks-phenix - gtk3 - sans gtklevelbar](https://cloud.githubusercontent.com/assets/2294605/11380329/a32174c0-92f5-11e5-8e53-2f1e749dbb12.png)

![a widget factory - clearlooks-phenix - gtk3 - avec gtklevelbar](https://cloud.githubusercontent.com/assets/2294605/11380331/aa5fe83e-92f5-11e5-8845-3e528cb03e3c.png)

**Comment by jpfleury** [comment]
There's a new release (Clearlooks-Phénix v7) that supports GTK 3.20. I don't plan to support older versions, so I close this report, but anyone can make a pull request.
