### ISSUE TITLE
Window border for native gnome 3 apps

### ISSUE THREAD

**Issue by jwc866** [jpfleury/clearlooks-phenix#27]
First I would like to say Thank You for this theme, it has been wonderful.
I am using version 6 on CentOS7/Gnome 3.14.  It seems the border for apps like Nautilus, gEdit, etc. is missing (no border).  All other apps are working great.  Is there a workaround or fix for this?  Thank you in advance.

**Comment by jwc866** [comment]
I found a workaround for now by adding a "box-shadow" line to gtk-3.0/gtk-widgets.css, to add a shadow to the windows like this:

.window-frame {
        border-width: 1px;
        border-radius: 7px 7px 0 0;
        border-style: solid;
        margin: 10px;
        box-shadow: 0 2px 8px 3px alpha(black, 0.5);
}

Not sure if there is a better way or permanent fix?  Thanks!

**Comment by jpfleury** [comment]
There's a new release (Clearlooks-Phénix v7) that supports GTK 3.20. I don't plan to support older versions, so I close this report, but anyone can make a pull request.
