### ISSUE TITLE
GTK 3.20

### ISSUE THREAD

**Issue by de-vri-es** [jpfleury/clearlooks-phenix#28]
GTK 3.20 again broke backwards compatibility for themes. This time they're promising stable naming so I suppose that this might be the last time they break themes. Who knows.

I'm not really up to speed, and I couldn't find a comprehensive list of what changed.
This link promises documented node names, but I can't find them:
https://blogs.gnome.org/mclasen/2015/11/20/a-gtk-update/

Unless it's the list of defines at the bottom here:
https://developer.gnome.org/gtk3/stable/GtkStyleContext.html
I'm not familiar with GTK theming or GTK at all, so I don't know if that is the relevant information.

P.S.
Everyone contributing to this theme: thank you. It's the one things that makes GTK 3 bearable.

**Comment by calestyo** [comment]
I collected a number of issues I've noted at http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=821409 some of them may actually be GTK issues, since it doesn't work with Adwaita either.

**Comment by bencaradocdavies** [comment]
firefox 45.0.2-1 is horribly broken on debian/unstable with clearlooks-phenix. Symptoms are most space around menu buttons and menu items is missing, dialog buttons lack their outlines, and all mouseover highlighting is missing.

**Comment by andrewshadura** [comment]
https://www.bountysource.com/issues/32831473-gtk-3-20 :)

**Comment by hishamhm** [comment]
Just to confirm the bug, I'm having the exact same issues on Firefox as @bencaradocdavies.

**Comment by hishamhm** [comment]
Just found another Clearlooks port that works on 3.20: Mate's TraditionalOk:

https://github.com/mate-desktop/mate-themes/tree/master/desktop-themes/TraditionalOk

**Comment by calestyo** [comment]
TraditionalOk, doesn't work (at least in Debian sid) either.

**Comment by de-vri-es** [comment]
Maybe Debian is shipping an old version? You could try from source.

**Comment by de-vri-es** [comment]
The version shipped with Arch is working great as far as I can tell. Thanks for the tip @hishamhm .

**Comment by dilworks** [comment]
Unfortunately TraditionalOK doesn't really blend under GTK3. It looks... so off.
So nope, not an acceptable workaround for me :/

And I'm in a dire situation right now, since MATE 1.14 landed with its massive switchover to GTK3 in Debian Testing, and I can't stand those constant theme breakages because someone at GNOME keeps having UX ephiphanes every 3 months.

So... is there any hope for a fix?

**Comment by bencaradocdavies** [comment]
Looks fixed in Debian unstable clearlooks-phenix-theme 6.0.3+git20161006-2; see #32.

**Comment by jpfleury** [comment]
Fixed in Clearlooks-Phénix v7.

**Comment by dilworks** [comment]
Well, it's working...

...except that things like menubars now look freakin' tall! Almost as tall as toolbars, but not quite.
There is now a ~4px margin on top of bottom of menus that should not be there. This also causes the MATE panel to display oversized systray icons if a panel contains a menubar widget.

**Comment by andrewshadura** [comment]
Could you please post a screenshot?

Thanks.

-- 
Cheers,
  Andrew

**Comment by dilworks** [comment]
OK, here is a example with MATE desktop running Pluma:
http://i.imgur.com/ogwcEJH.png

Look at the menubars (I've thrown a GTK2 app -Seamonkey- as comparison). On this screenshot you can see the extra margin when a menu is open:
http://i.imgur.com/nhoFF11.png
(The menu itself renders fine)

Bonus bug: on that Pluma screenshot take a look at the status bar. Notice that borders render outside the statusbar area, reaching the document workspace (those two items in the middle are actually buttons that open dropdown menus too, might be the same thing?)
