### ISSUE TITLE
GTK3 3.18.9 Caja 1.14 vertical line spacing

### ISSUE THREAD

**Issue by burdi01** [jpfleury/clearlooks-phenix#29]
On Slackware64 Current Multilib with GTK 2.2.24 and 3.18.9, XFCE 4.12 and the Clearlooks-Phenix v6 theme I compared Caja, Atril, Engrampa and Pluma from willysr's 1.14 GTK2 and GTK3 builds at http://slackware.uk/msb/testing/.
I found that for GTK3 the Caja line mode "zebra" background effect that I see with GTK2 is gone, and that the vertical line spacing is wider than with GTK2: a full height window lists 35 vs 38 lines.
I see the same wider line spacing with Mate's TraditionOK theme, but *not* with the Gnome's builtin (?) Adwaita theme.

**Comment by jpfleury** [comment]
There's a new release (Clearlooks-Phénix v7) that supports GTK 3.20. I don't plan to support GTK 3.18, so I close this report, but anyone can make a pull request about GTK 3.18.
