### ISSUE TITLE
px missing in text-shadow of Nautilus

### ISSUE THREAD

**Issue by jkotan** [jpfleury/clearlooks-phenix#30]
Hello,

After  uncommenting the Nautilus part of applications.css I get the following error:

    Gtk-WARNING **: Theme parsing error: applications.css:8:15: Not using units is deprecated. Assuming 'px'.
    Gtk-WARNING **: Theme parsing error: applications.css:8:17: Not using units is deprecated. Assuming 'px'.

It seems that px are missing, i.e. it should be:

     .nautilus-desktop.nautilus-canvas-item {
        color: @theme_base_color;
        text-shadow: 1px 1px alpha (@theme_fg_color, 0.8);
    }

BTW, is there any reason that icon fonts are by default black? For dark backgrounds it looks horribile, i.e. it is hard to read the icon text.

Best regards,
Jan

**Comment by jpfleury** [comment]
There's a new release (Clearlooks-Phénix v7) that supports GTK 3.20. I don't plan to support older versions, so I close this report, but anyone can make a pull request.
